
if [ module-info mode load ] {
  if [ is-loaded PrgEnv-intel ] {
  } else {
    if [ is-loaded PrgEnv-cray ] {
      module swap PrgEnv-cray PrgEnv-intel
    }
    if [ is-loaded PrgEnv-gnu ] {
      module swap PrgEnv-gnu PrgEnv-intel
    }
  }
  module swap craype-haswell craype-mic-knl
  module swap intel intel/17.0.2.174
  module load gcc/6.3.0
  module load cmake
  module load git
  setenv CRAYPE_LINK_TYPE dynamic
}
