FROM ubuntu:16.04

MAINTAINER Theodore Kisner <tskisner@lbl.gov>

# Use bash

SHELL ["/bin/bash", "-c"]

# Install system dependencies.

RUN apt-get update \
    && apt-get install -y curl procps build-essential gfortran git subversion \
    python libcairo2-dev libpixman-1-dev libgsl-dev flex pkg-config cmake \
    autoconf m4 libtool automake locales libopenblas-dev liblapacke-dev \
    && rm -fr /var/lib/apt/lists/*

# Set up locales, to workaround a pip bug

RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

# We install everything directly into /usr so that we do
# not need to modify the default library and executable
# search paths.  Shifter will manipulate LD_LIBRARY_PATH,
# so it is important not to use that variable.

# Create working directory for builds

RUN mkdir /usr/src/desi
WORKDIR /usr/src/desi

# Install conda root environment

ENV PYTHONPATH ""
ENV PYTHONSTARTUP ""
ENV PYTHONNOUSERSITE "1"
ENV PYTHONUSERBASE "/tmp"

@conda_root@

ENV ACCEPT_INTEL_PYTHON_EULA yes

@conda_intel@

# Install conda packages.

@conda_pkgs@

# Install pip packages.

@pip_pkgs@

# The conda TCL packages overwrite the system-installed regex.h.  So
# now we force reinstall of the package that provides that

RUN apt-get update \
    && apt-get install -y --reinstall libc6-dev \
    && rm -fr /var/lib/apt/lists/*

# Copy all patch files to current working directory

RUN mkdir ./rules
ADD rules/patch_* ./rules/

# Install MPICH 3.2 which is compatible with the external
# Cray MPICH which is prepended to LD_LIBRARY_PATH as part
# of shifter.

@mpich@

# Install mpi4py.

@mpi4py@

# Install CFITSIO.

@cfitsio@

@fitsverify@

# Install FFTW.

@fftw@

# Install BOOST.

@boost@

# GalSim and dependencies

@scons@

@tmv@

@galsim@

# Image libraries needed by astrometry

@bzip2@

@libz@

@libpng@

@libjpeg@

@libtiff@

# wcslib

@wcslib@

# pcre

@pcre@

# swig

@swig@

# ceres

@metis@

@glog@

@eigen@

@suitesparse@

@ceres@

# astrometry.net
# This package and tractor install python tools to a "lib/python"
# directory rather than site-packages.  Make a symlink here.

RUN ln -s "@AUX_PREFIX@/lib/python@PYVERSION@/site-packages" "@AUX_PREFIX@/lib/python"

@astrometry_net@

# tractor

@tractor@

# Astromatic toolkit pieces

@sextractor@

@psfex@

@cdsclient@

@scamp@

@swarp@

# Remove the temporary patches

RUN rm -rf ./rules

# Precompile all python modules.  Ignore errors.

RUN python -m compileall -f "/usr/lib/python@PYVERSION@/site-packages"; exit 0

# Create a fake home directory so that packages can create
# config files if needed

RUN mkdir /home/desi
RUN mkdir /home/desi/.astropy

WORKDIR /home/desi
ENV HOME /home/desi

RUN python -c "import astropy"
RUN python -c "import matplotlib.font_manager as fm; f = fm.FontManager"

# Set the entrypoint and default command

ENTRYPOINT ["/bin/bash", "-c"]
CMD ["/bin/bash"]
